### ISSUE TITLE
Hang on upload of large image

### ISSUE THREAD

**Issue by extrajoss** [ODonoghueLab/versus#41]
I tried creating an experiment. I uploaded some random images and clicked submit. 

on the console I can see 
POST /api/rpc-upload - - ms - -
>> router.rpc-upload.uploadImagesAndCreateExperiment
>> router.storeFiles error: Error: Please Keep Images Under 2MB
    at Object.storeFiles (/Users/jos031/Code/Repos/versus/server/src/models.js:134:13)
    at uploadImagesAndCreateExperiment (/Users/jos031/Code/Repos/versus/server/src/handlers.js:310:32)
    at router.post (/Users/jos031/Code/Repos/versus/server/src/router.js:139:5)
    at Layer.handle [as handle_request] (/Users/jos031/Code/Repos/versus/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/jos031/Code/Repos/versus/server/node_modules/express/lib/router/route.js:131:13)
    at Array.<anonymous> (/Users/jos031/Code/Repos/versus/server/node_modules/multer/lib/make-middleware.js:53:37)
    at listener (/Users/jos031/Code/Repos/versus/server/node_modules/on-finished/index.js:169:15)
    at onFinish (/Users/jos031/Code/Repos/versus/server/node_modules/on-finished/index.js:100:5)
    at callback (/Users/jos031/Code/Repos/versus/server/node_modules/ee-first/index.js:55:10)
    at Socket.onevent (/Users/jos031/Code/Repos/versus/server/node_modules/ee-first/index.js:93:5)
    at emitOne (events.js:120:20)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:547:12)
>> router.rollback delete /Users/jos031/Code/Repos/versus/server/files/45d3bb6d2062299e3b8f71821cd9e4cd
>> router.rollback delete /Users/jos031/Code/Repos/versus/server/files/ce7254a90073e582b349ba5e29666737
>> router.rollback delete /Users/jos031/Code/Repos/versus/server/files/bc61b61d2ab6c6e4e6c39a296349db7e
>> router.rollback delete /Users/jos031/Code/Repos/versus/server/files/c155f9645341c8ff701988976bce326a
>> router.rollback delete /Users/jos031/Code/Repos/versus/server/files/951c1d31545b27f820b56a3401174ae9
>> router.rollback delete /Users/jos031/Code/Repos/versus/server/files/05381d1dcbc85e509622853baa0436dd
>> router.rollback delete /Users/jos031/Code/Repos/versus/server/files/7869f338c744fc6ca67f35444b243bf7
>> router.rollback delete /Users/jos031/Code/Repos/versus/server/files/01449e09c71b40da9f7963e776cddbcd
>> router.rollback delete /Users/jos031/Code/Repos/versus/server/files/6ddb85d6083e41b24b72fbb070c01588
>> router.rollback delete /Users/jos031/Code/Repos/versus/server/files/bc28b6f86b05e45ddefde27df30bc71f
>> router.rollback delete /Users/jos031/Code/Repos/versus/server/files/e2f4091ec557ed75ec19b72daebaff12
>> router.rollback delete /Users/jos031/Code/Repos/versus/server/files/7a7dfea0bdb8dee4d5153a3e76b89b7d
>> router.rollback delete /Users/jos031/Code/Repos/versus/server/files/a6f90f701bcedf986f4d529d271bf91d
>> router.rollback delete /Users/jos031/Code/Repos/versus/server/files/1f61c3b1f4a2d4f4650f2ec3b29b6735
>> router.rollback delete /Users/jos031/Code/Repos/versus/server/files/c724e56698881a6b15d5555a7c303f52

but no feedback on the client. Just hangs in waiting state.

**Comment by boscoh** [comment]
fixed with https://github.com/ODonoghueLab/versus/commit/3577f7732126312c8d3e854f3b17505d226a7f38
